# Input file for variable settings

# May your variable be stored in the fine scale mesh entities or in the coarse mesh entities? (0 for fine scale, 1 for coarse scale)

scale:

# Inform us the name of the variable you want to create, its data size and format in the following form:

# name of entity:
#   - name of variable
#     - data size (must be an integer)
#     - data format (must be a string: 'int', 'float')

# Pay attention to identation!

nodes:

edges:

faces:

volumes:
