# Input file for variable settings

# Inform us the name of the variable you want to create, its data size, format and the level of mesh in which the variable must be stored (pay attetion to the identation!):

nodes:
  happiness:
    data size: 1
    data format: 'float'
    level: 0

edges:
  joy:
    data size: 1
    data format: 'float'
    level: 0

faces:
  pride:
    data size: 1
    data format: 'float'
    level: 0

volumes:
  dreams:
    data size: 1
    data format: 'float'
    level: 0
